# Generated by Django 4.2 on 2023-06-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscribers_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
