# Generated by Django 4.2 on 2023-05-15 06:10

from django.db import migrations, models
import apps.videos.validators


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='videos',
            field=models.FileField(upload_to='videos/media/', validators=[apps.videos.validators.validate_video_extension]),
        ),
    ]
