# Generated by Django 4.2 on 2023-05-15 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_alter_videos_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
