# Generated by Django 4.2 on 2023-05-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_videos_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='image',
            field=models.ImageField(default=None, upload_to='videos/media/'),
            preserve_default=False,
        ),
    ]
