# Generated by Django 4.2 on 2023-05-17 13:16

from django.db import migrations, models
import apps.videos.validators


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_videos_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='image',
            field=models.ImageField(upload_to='D:\\Programming\\Py\\PyProjects\\.AllProject\\Youtube\\youtube\\media//images'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='videos',
            field=models.FileField(upload_to='D:\\Programming\\Py\\PyProjects\\.AllProject\\Youtube\\youtube\\media//videos', validators=[apps.videos.validators.validate_video_extension]),
        ),
    ]
