# Generated by Django 4.2 on 2023-05-17 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_alter_videos_image_alter_videos_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videos',
            old_name='videos',
            new_name='video_file',
        ),
    ]
